run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - gosimple
    - typecheck
    - unused
    - gocritic
  disable:
    - depguard

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

